# Generated by Django 3.2.3 on 2022-07-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modal',
            name='pdf',
            field=models.FileField(default='empty', upload_to='modal/pdf'),
        ),
    ]
