# Generated by Django 3.2.3 on 2022-07-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_modal_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modal',
            name='pdf',
            field=models.FileField(blank=True, default='empty', upload_to='modal/pdf'),
        ),
        migrations.AlterField(
            model_name='modal',
            name='story',
            field=models.TextField(blank=True),
        ),
    ]
