# Generated by Django 3.2.3 on 2022-07-09 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20220709_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='row',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.row'),
        ),
    ]
