# Generated by Django 3.2.3 on 2022-07-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20220709_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='icon',
            field=models.ImageField(default='default_icon.png', upload_to=''),
        ),
    ]
