# Generated by Django 3.2.3 on 2022-07-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
