# Generated by Django 3.2.3 on 2022-08-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_item_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, default='empty', upload_to='page/pdf')),
                ('iframe', models.TextField(blank=True)),
                ('claps', models.IntegerField(default=0)),
                ('is_game', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Modal',
        ),
    ]
