# Generated by Django 3.2.3 on 2022-08-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20220820_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='none', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
