# Generated by Django 3.2.3 on 2022-08-20 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='author',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
