# Generated by Django 3.2.3 on 2022-08-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20220820_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='claps',
            new_name='hearts',
        ),
    ]
