# Generated by Django 3.2.3 on 2022-08-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_rename_claps_page_hearts'),
    ]

    operations = [
        migrations.CreateModel(
            name='lovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='hearts',
        ),
        migrations.AddField(
            model_name='page',
            name='hearts',
            field=models.ManyToManyField(blank=True, related_name='page_hearts', to='portfolio.lovers'),
        ),
    ]
