# Generated by Django 3.2.3 on 2022-08-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20220820_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lovers',
            new_name='Lover',
        ),
    ]
