# Generated by Django 4.1.3 on 2023-02-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_rename_lovers_lover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='page',
            name='updated_on',
        ),
    ]
