# Generated by Django 4.1.3 on 2023-03-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_page_created_on_page_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='iframe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='pdf',
            field=models.FileField(blank=True, default='empty', null=True, upload_to='page/pdf'),
        ),
        migrations.AlterField(
            model_name='page',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
