# Generated by Django 4.1.3 on 2023-03-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_article_conent_article_content_rendered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
