# Generated by Django 4.1.3 on 2023-03-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_remove_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='position',
        ),
    ]
