# Generated by Django 4.1.3 on 2023-03-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='conent',
            new_name='content',
        ),
    ]
