# Generated by Django 4.1.3 on 2023-03-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_rename_conent_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hearts',
            field=models.ManyToManyField(blank=True, related_name='article_hearts', to='portfolio.lover'),
        ),
    ]
