# Generated by Django 4.1.3 on 2023-03-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_remove_page_hearts_alter_article_hearts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hearts',
        ),
        migrations.DeleteModel(
            name='Lover',
        ),
    ]
