# Generated by Django 4.1.3 on 2023-03-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_remove_article_hearts_delete_lover'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
