# Generated by Django 4.1.3 on 2023-03-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_article_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='v3slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
