# Generated by Django 4.1.3 on 2023-03-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_article_v3slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_rendered',
        ),
        migrations.RemoveField(
            model_name='article',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='start_date',
        ),
    ]
