# Generated by Django 4.1.3 on 2023-08-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0030_remove_article_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("published", models.DateField()),
                ("public", models.BooleanField(default=False)),
                ("featured", models.BooleanField(default=False)),
                ("school", models.BooleanField(default=False)),
                ("work", models.BooleanField(default=False)),
                ("pet", models.BooleanField(default=False)),
                ("blog", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db", models.JSONField()),
            ],
        ),
    ]
