# Generated by Django 4.1.3 on 2023-08-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0031_post_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateField(null=True),
        ),
    ]
