# Generated by Django 4.1.3 on 2023-08-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0033_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
