# Generated by Django 4.1.3 on 2023-08-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0034_post_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover",
            field=models.URLField(blank=True, default=None),
        ),
    ]
