# Generated by Django 4.1.3 on 2023-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0040_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
