# Generated by Django 4.1.3 on 2023-08-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0042_alter_post_name_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="name",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
